### ISSUE TITLE
Homepage not updated

### ISSUE THREAD

**Issue by martinheidegger** [datproject/public-events#10]
Probably similar to https://github.com/datproject/comm-comm/issues/129 it seems like the homepage is not update in netlify?!

**Comment by martinheidegger** [comment]
ping @okdistribute

**Comment by okdistribute** [comment]
cc @joehand

**Comment by joehand** [comment]
Just did a manual deploy and it worked. Hopefully auto deploys will work? Looks like the repo was already links to here instead of dat-land which is what I had done to fix comm-comm.

**Comment by dpaez** [comment]
Thank you very much Joe!
