### ISSUE TITLE
Website broken in Firefox after recent push

### ISSUE THREAD

**Issue by Frando** [datproject/public-events#12]
Frontpage works fine, if I click on 2020 or 2019, I get this error:

![foo](https://user-images.githubusercontent.com/43627/80487659-7a988080-895d-11ea-823c-64ca28a11db5.png)

Firefox 75.0 on Arch Linux that is. Chromium works fine. Is this me or others as well?

**Comment by Frando** [comment]
It seems that gzip content is served without that being announced properly. Response likely misses the "Content-Encoding: gzip" header

**Comment by martinheidegger** [comment]
@Frando Are you sure that no plugin of yours is interfering here?

**Comment by martinheidegger** [comment]
Can you test if a hard-refresh Ctrl+Shift+R makes a difference?

**Comment by martinheidegger** [comment]
Maybe a service-worker issue: (good read → https://bugzilla.mozilla.org/show_bug.cgi?id=1503072)

**Comment by Frando** [comment]
I don't think its me or service workers:

Try `curl -H "Accept-Encoding: gzip, deflate" -v https://events.dat.foundation/2020` - it returns a gzip encoded payload, but the response doesn't have the required `Content-Encoding: gzip` header.

**Comment by martinheidegger** [comment]
I had the same error in chrome/Firefox - a hard reload solved it for me.
That being said: it needs to be fixed.
