### ISSUE TITLE
Add Social image to events page

### ISSUE THREAD

**Issue by martinheidegger** [datproject/public-events#13]
Have an image for the social networks (twitter, etc) for the dat event.

**Comment by martinheidegger** [comment]
<img width="488" alt="Screen Shot 2020-07-09 at 06 33 05" src="https://user-images.githubusercontent.com/914122/86972544-193b2c00-c1ae-11ea-9a82-f8779b8bd203.png">

**Comment by martinheidegger** [comment]
I prepared this banner for the page ↓

![dat-event-2020-banner](https://user-images.githubusercontent.com/914122/87055620-8ba81c80-c23f-11ea-8b73-7e041250e72a.png)

**Comment by ssaavedra** [comment]
Should we use the datgreeen colour for the July 30/31 instead of the alert one? I'll grab this and add it to the OG card

**Comment by martinheidegger** [comment]
Which do you like better?
![dat-event-2020-banner](https://user-images.githubusercontent.com/914122/87419944-591b6c80-c60f-11ea-9199-46f91f4fdaef.png)

**Comment by ssaavedra** [comment]
Closed at commits  755fc262 and  48c7fdb
