### ISSUE TITLE
org: add github repo owner

### ISSUE THREAD

**Issue by martinheidegger** [datproject/public-events#5]
Add "events"-github group as owner.

**Comment by okdistribute** [comment]
done

**Comment by martinheidegger** [comment]
Thank you for adding it, but it is only "read" access. 😅 

<img width="1002" alt="Screen Shot 2020-03-19 at 03 29 18" src="https://user-images.githubusercontent.com/914122/76994516-d997cc80-6991-11ea-93c7-99138145433b.png">

**Comment by okdistribute** [comment]
too many buttons!

**Comment by martinheidegger** [comment]
![](https://media.giphy.com/media/9DavVitIZ26jH0aK7s/giphy.gif)
