### ISSUE TITLE
New Domain?

### ISSUE THREAD

**Issue by martinheidegger** [datproject/public-events#6]
Currently this repo is linked to https://events.datproject.org/ but since the dat homepage moved to dat.foundation, would it be better to move it there?

**Comment by RangerMauve** [comment]
I can help set up the DNS and netlify stuff for this if it's something we want. 😁

**Comment by martinheidegger** [comment]
@okdistribute what do you think?

**Comment by okdistribute** [comment]
sure!

**Comment by okdistribute** [comment]
sure!

**Comment by RangerMauve** [comment]
Set up the cloudflare DNS and netlify naming for https://events.dat.foundation/

Might want to update the `_redirect` file to point to that for when people use the old datproject URL.

**Comment by RangerMauve** [comment]
It'd be nice if someone could PR the dat foundation website to link to the events website.
